-- Insert subcategories for each category
-- Note: These subcategory IDs are generated by Supabase (uuid), so we reference by slug

-- Plumbing subcategories
INSERT INTO subcategories (category_id, name, slug, description, sort_order)
SELECT id, 'Leak repair', 'leak_repair', 'Faucets, pipes, drainage', 1 FROM categories WHERE slug = 'plumbing';

INSERT INTO subcategories (category_id, name, slug, description, sort_order)
SELECT id, 'Installation', 'installation', 'Fixtures and appliances', 2 FROM categories WHERE slug = 'plumbing';

-- Electrical subcategories
INSERT INTO subcategories (category_id, name, slug, description, sort_order)
SELECT id, 'Wiring', 'wiring', 'Panels, outlets, lighting', 1 FROM categories WHERE slug = 'electrical';

INSERT INTO subcategories (category_id, name, slug, description, sort_order)
SELECT id, 'Repairs', 'repairs', 'Faults and replacements', 2 FROM categories WHERE slug = 'electrical';

-- Carpentry subcategories
INSERT INTO subcategories (category_id, name, slug, description, sort_order)
SELECT id, 'Furniture', 'furniture', 'Build and repair', 1 FROM categories WHERE slug = 'carpentry';

INSERT INTO subcategories (category_id, name, slug, description, sort_order)
SELECT id, 'Frames & doors', 'frames_doors', 'Install and adjust', 2 FROM categories WHERE slug = 'carpentry';

-- Cleaning subcategories
INSERT INTO subcategories (category_id, name, slug, description, sort_order)
SELECT id, 'Deep clean', 'deep_clean', 'Home and office', 1 FROM categories WHERE slug = 'cleaning';

INSERT INTO subcategories (category_id, name, slug, description, sort_order)
SELECT id, 'Move-in/out', 'move_in_out', 'Full property clean', 2 FROM categories WHERE slug = 'cleaning';

-- Painting subcategories
INSERT INTO subcategories (category_id, name, slug, description, sort_order)
SELECT id, 'Interior', 'interior', 'Walls and ceilings', 1 FROM categories WHERE slug = 'painting';

INSERT INTO subcategories (category_id, name, slug, description, sort_order)
SELECT id, 'Exterior', 'exterior', 'Outdoor surfaces', 2 FROM categories WHERE slug = 'painting';

-- Construction subcategories
INSERT INTO subcategories (category_id, name, slug, description, sort_order)
SELECT id, 'Renovation', 'renovation', 'Remodeling work', 1 FROM categories WHERE slug = 'construction';

INSERT INTO subcategories (category_id, name, slug, description, sort_order)
SELECT id, 'Structural repair', 'structural_repair', 'Masonry and builds', 2 FROM categories WHERE slug = 'construction';

-- HVAC subcategories
INSERT INTO subcategories (category_id, name, slug, description, sort_order)
SELECT id, 'AC service', 'ac_service', 'Cooling units', 1 FROM categories WHERE slug = 'hvac';

INSERT INTO subcategories (category_id, name, slug, description, sort_order)
SELECT id, 'Heating', 'heating', 'Boilers and heaters', 2 FROM categories WHERE slug = 'hvac';

-- Landscaping subcategories
INSERT INTO subcategories (category_id, name, slug, description, sort_order)
SELECT id, 'Lawn care', 'lawn_care', 'Mowing and trimming', 1 FROM categories WHERE slug = 'landscaping';

INSERT INTO subcategories (category_id, name, slug, description, sort_order)
SELECT id, 'Garden design', 'garden_design', 'Plants and layout', 2 FROM categories WHERE slug = 'landscaping';

ON CONFLICT DO NOTHING;
