-- Expand service catalog to better reflect common Ghanaian artisan trades.
-- Idempotent: existing slugs are updated, new slugs are inserted.

INSERT INTO categories (name, slug, icon_name, color_hex, description, sort_order) VALUES
  ('Plumbing',                    'plumbing',         'drop',         '#4648D4', 'Repairs, installation, maintenance',                  1),
  ('Electrical',                  'electrical',       'lightning',    '#0058BE', 'Wiring, repairs, installations',                      2),
  ('Carpentry',                   'carpentry',        'wrench',       '#B55D00', 'Furniture, cabinets, doors, woodwork',                3),
  ('Masonry & Blockwork',          'masonry',          'bricks',       '#8B5E3C', 'Blocks, plastering, concrete and masonry repairs',    4),
  ('Welding & Fabrication',        'welding',          'fire',         '#607D8B', 'Metal gates, burglar proofing and fabrication',        5),
  ('Construction & Renovation',    'construction',     'barricade',    '#FF9800', 'Building, renovation and structural repairs',          6),
  ('Automotive & Small Engine',    'automotive',       'car',          '#795548', 'Vehicle, motorbike and small engine repairs',          7),
  ('Painting',                    'painting',         'palette',      '#F44336', 'Interior, exterior and decorative painting',           8),
  ('Tiling & Flooring',            'tiling',           'squares_four', '#009688', 'Floor tiles, wall tiles and floor finishing',          9),
  ('Roofing & Ceiling',            'roofing',          'house_line',   '#9C27B0', 'Roofing sheets, ceiling panels and leak fixes',        10),
  ('HVAC & Refrigeration',         'hvac',             'snowflake',    '#2196F3', 'Cooling, refrigeration and ventilation',               11),
  ('Appliance & Electronics Repair','appliance_repair','plug',         '#3F51B5', 'Home appliances, electronics and diagnostics',          12),
  ('Cleaning',                    'cleaning',         'broom',        '#00A86B', 'Home, office and deep cleaning',                       13),
  ('Landscaping',                 'landscaping',      'mountains',    '#4CAF50', 'Lawn, garden and outdoor maintenance',                 14),
  ('Fashion & Dressmaking',        'fashion',          'scissors',     '#E91E63', 'Tailoring, alterations and garment making',            15),
  ('Hair & Beauty',                'beauty',           'scissors',     '#AD1457', 'Hairdressing, barbering and beauty services',          16),
  ('Catering & Events',            'catering',         'fork_knife',   '#C15A3D', 'Cooking, baking and event food services',              17),
  ('Upholstery',                  'upholstery',       'armchair',     '#6D4C41', 'Sofas, cushions, curtains and soft furnishings',       18),
  ('Security & Locksmith',         'security',         'lock_key',     '#455A64', 'Locks, keys, burglar proofing and access repairs',     19),
  ('ICT & Device Support',         'ict_support',      'desktop_tower','#1565C0', 'Computer, phone, network and device support',          20)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  icon_name = EXCLUDED.icon_name,
  color_hex = EXCLUDED.color_hex,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  is_active = true;

INSERT INTO subcategories (category_id, name, slug, description, sort_order)
SELECT c.id, s.name, s.slug, s.description, s.sort_order
FROM categories c
JOIN (VALUES
  ('plumbing', 'Leak repair', 'leak_repair', 'Faucets, pipes, tanks and drainage leaks', 1),
  ('plumbing', 'Installation', 'installation', 'Fixtures, sinks, toilets and pumps', 2),
  ('plumbing', 'Drainage & septic', 'drainage_septic', 'Blocked drains, soakaways and septic issues', 3),
  ('electrical', 'Wiring', 'wiring', 'Panels, outlets, sockets and lighting', 1),
  ('electrical', 'Repairs', 'repairs', 'Faults, trips and replacements', 2),
  ('electrical', 'Generator & inverter', 'generator_inverter', 'Generator, inverter and backup power support', 3),
  ('carpentry', 'Furniture', 'furniture', 'Build and repair furniture', 1),
  ('carpentry', 'Frames & doors', 'frames_doors', 'Install and adjust doors, frames and locks', 2),
  ('carpentry', 'Cabinets & wardrobes', 'cabinets_wardrobes', 'Kitchen cabinets, wardrobes and shelving', 3),
  ('masonry', 'Block laying', 'block_laying', 'Blockwork, walls and partitions', 1),
  ('masonry', 'Plastering', 'plastering', 'Wall plastering and screeding', 2),
  ('masonry', 'Concrete repair', 'concrete_repair', 'Concrete, steps and surface repairs', 3),
  ('welding', 'Metal gates', 'metal_gates', 'Gates, frames and metal doors', 1),
  ('welding', 'Burglar proofing', 'burglar_proofing', 'Window bars and security grills', 2),
  ('welding', 'Fabrication repair', 'fabrication_repair', 'Welding repairs and custom metal work', 3),
  ('construction', 'Renovation', 'renovation', 'Remodeling and general renovation', 1),
  ('construction', 'Structural repair', 'structural_repair', 'Masonry, concrete and structural fixes', 2),
  ('construction', 'Site labour', 'site_labour', 'General construction labour and finishing', 3),
  ('automotive', 'Car mechanic', 'car_mechanic', 'Diagnosis, servicing and repairs', 1),
  ('automotive', 'Motorbike repair', 'motorbike_repair', 'Motorbike and tricycle repairs', 2),
  ('automotive', 'Auto body & spraying', 'auto_body_spraying', 'Body work, spraying and panel repairs', 3),
  ('painting', 'Interior', 'interior', 'Walls, ceilings and rooms', 1),
  ('painting', 'Exterior', 'exterior', 'Outdoor surfaces and weather coating', 2),
  ('painting', 'Decorative finish', 'decorative_finish', 'Texture, patterns and special finishes', 3),
  ('tiling', 'Floor tiling', 'floor_tiling', 'Floor tile installation and replacement', 1),
  ('tiling', 'Wall tiling', 'wall_tiling', 'Kitchen, bathroom and wall tiles', 2),
  ('tiling', 'Terrazzo & floor finish', 'terrazzo_floor_finish', 'Terrazzo, screed and floor finishing', 3),
  ('roofing', 'Roof installation', 'roof_installation', 'Roofing sheets, trusses and installation', 1),
  ('roofing', 'Ceiling work', 'ceiling_work', 'PVC, POP and panel ceilings', 2),
  ('roofing', 'Roof leak repair', 'roof_leak_repair', 'Leak tracing and roof patching', 3),
  ('hvac', 'AC service', 'ac_service', 'Air conditioners and cooling units', 1),
  ('hvac', 'Refrigeration', 'refrigeration', 'Fridges, freezers and cold rooms', 2),
  ('hvac', 'Ventilation', 'ventilation', 'Fans, ducts and airflow', 3),
  ('appliance_repair', 'Kitchen appliances', 'kitchen_appliances', 'Cookers, blenders, microwaves and kettles', 1),
  ('appliance_repair', 'Laundry appliances', 'laundry_appliances', 'Washing machines and irons', 2),
  ('appliance_repair', 'Electronics repair', 'electronics_repair', 'TVs, audio and household electronics', 3),
  ('cleaning', 'Deep clean', 'deep_clean', 'Home and office deep cleaning', 1),
  ('cleaning', 'Move-in/out', 'move_in_out', 'Full property clean', 2),
  ('cleaning', 'Fumigation & pest control', 'fumigation_pest_control', 'Pest control and fumigation', 3),
  ('landscaping', 'Lawn care', 'lawn_care', 'Mowing and trimming', 1),
  ('landscaping', 'Garden design', 'garden_design', 'Plants and layout', 2),
  ('landscaping', 'Compound cleanup', 'compound_cleanup', 'Weeding and outdoor clearing', 3),
  ('fashion', 'Dressmaking', 'dressmaking', 'New garments and custom outfits', 1),
  ('fashion', 'Alterations', 'alterations', 'Resizing, repairs and adjustments', 2),
  ('fashion', 'School & work uniforms', 'school_work_uniforms', 'Uniform sewing and repairs', 3),
  ('beauty', 'Hairdressing', 'hairdressing', 'Braids, styling and treatments', 1),
  ('beauty', 'Barbering', 'barbering', 'Haircuts, grooming and shaving', 2),
  ('beauty', 'Makeup & nails', 'makeup_nails', 'Makeup, nails and beauty prep', 3),
  ('catering', 'Home cooking', 'home_cooking', 'Home meals and small gatherings', 1),
  ('catering', 'Baking', 'baking', 'Cakes, pastries and baked goods', 2),
  ('catering', 'Event catering', 'event_catering', 'Food for parties and events', 3),
  ('upholstery', 'Sofa repair', 'sofa_repair', 'Sofa frames, cushions and covering', 1),
  ('upholstery', 'Curtains & blinds', 'curtains_blinds', 'Curtain sewing and blind fitting', 2),
  ('upholstery', 'Cushions & covers', 'cushions_covers', 'Cushions, covers and soft furnishings', 3),
  ('security', 'Locksmith', 'locksmith', 'Keys, locks and lockouts', 1),
  ('security', 'Burglar proofing', 'security_burglar_proofing', 'Security bars and metal protection', 2),
  ('security', 'CCTV & access', 'cctv_access', 'Cameras, doorbells and access support', 3),
  ('ict_support', 'Computer repair', 'computer_repair', 'Laptops, desktops and software setup', 1),
  ('ict_support', 'Phone repair', 'phone_repair', 'Phones, screens and accessories', 2),
  ('ict_support', 'Network setup', 'network_setup', 'Routers, Wi-Fi and small office networks', 3)
) AS s(category_slug, name, slug, description, sort_order)
  ON c.slug = s.category_slug
ON CONFLICT (category_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  is_active = true;
